// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhKcAfKzenwcJsrEqdazswv5M-Hl-d6g',
    appId: '1:1053462322225:web:5ac11b84a1a227ac120910',
    messagingSenderId: '1053462322225',
    projectId: 'food-app-4f344',
    authDomain: 'food-app-4f344.firebaseapp.com',
    storageBucket: 'food-app-4f344.appspot.com',
    measurementId: 'G-799BYRJLGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwvBTInoJ7paEs8BdImOrFLYXOLkdUBM',
    appId: '1:1053462322225:android:ad420141978a5419120910',
    messagingSenderId: '1053462322225',
    projectId: 'food-app-4f344',
    storageBucket: 'food-app-4f344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpIkgKoDgpGkO_bddqDtJEK6HOYSfY2zE',
    appId: '1:1053462322225:ios:41322dfc758352bf120910',
    messagingSenderId: '1053462322225',
    projectId: 'food-app-4f344',
    storageBucket: 'food-app-4f344.appspot.com',
    iosClientId: '1053462322225-70uagecs745lohjeqqit1oe3b92bojsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpIkgKoDgpGkO_bddqDtJEK6HOYSfY2zE',
    appId: '1:1053462322225:ios:41322dfc758352bf120910',
    messagingSenderId: '1053462322225',
    projectId: 'food-app-4f344',
    storageBucket: 'food-app-4f344.appspot.com',
    iosClientId: '1053462322225-70uagecs745lohjeqqit1oe3b92bojsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZhKcAfKzenwcJsrEqdazswv5M-Hl-d6g',
    appId: '1:1053462322225:web:64d30d2215a624dd120910',
    messagingSenderId: '1053462322225',
    projectId: 'food-app-4f344',
    authDomain: 'food-app-4f344.firebaseapp.com',
    storageBucket: 'food-app-4f344.appspot.com',
    measurementId: 'G-66VTQSMCDD',
  );

}